### ISSUE TITLE
The hitboxes and layering need some work

### ISSUE THREAD

**Issue by Agent-Skinner** [Awesomeace140/RPG_engine#1]
![broken](https://user-images.githubusercontent.com/47220982/52306536-80b7d100-2955-11e9-8079-fdc0296f2d4c.png)
![layering issue](https://user-images.githubusercontent.com/47220982/52306542-84e3ee80-2955-11e9-84b0-6e9a3a6d6548.png)

**Comment by Awesomeace140** [comment]
This is a simple issue with the hitbox size on the tree. Currently, I use the same hitbox size for the tree as I do with the terrain, which is way too big. I'll have to program a separate, smaller hitbox just for trees. I'll definitely get around to doing that, but for now there are other things I'd like to get going like the battle system, re-spiriting, etc.

**Comment by Awesomeace140** [comment]
As of version 1.3.1, this has been fixed. Thank you for your submission.
